import type {
  ContractCategoryType,
  ContractClauseResiliationType,
  ContractClientQualiteType,
  ContractCompanyType,
  ContractConfidentialiteType,
  ContractDeviseType,
  ContractEauElectriciteType,
  ContractFournituresType,
  ContractGarantieType,
  ContractGarantieTypeType,
  ContractGarantieUniteType,
  ContractModePaiementTexteType,
  ContractPrestationType,
  ContractStatutType,
  ContractTrancheType,
  ContractTribunalType,
  ContractTypeBienType,
  ContractTypeType,
  ProjectType,
  STDelaiUnitType,
  STFormeJuridiqueType,
  STTrancheType,
} from '@/types/contractTypes';

export class UserClass {
  constructor(
    public readonly id: number,
    public first_name: string,
    public last_name: string,
    public email: string,
    public gender: string,
    public avatar: string | ArrayBuffer | null,
    public avatar_cropped: string | ArrayBuffer | null,
    public is_staff: boolean,
    public is_active: boolean,
    public default_password_set: boolean,
    public date_joined: string | null,
    public date_updated: string | null,
    public last_login: string | null,
    // Per-user permission flags
    public can_view: boolean,
    public can_print: boolean,
    public can_create: boolean,
    public can_edit: boolean,
    public can_delete: boolean,
  ) {
  }
}

export class ContractClass {
  constructor(
    // Meta identifiers
    public readonly id: number,
    public numero_contrat: string,
    public readonly client_name: string | null,
    // Company
    public company: ContractCompanyType | string,
    public readonly company_display: string,
    public contract_category: ContractCategoryType | string,
    public readonly contract_category_display: string,
    // Client embedded fields
    public client_nom: string | null,
    public client_cin: string | null,
    public client_qualite: ContractClientQualiteType | string | null,
    public client_adresse: string | null,
    public client_tel: string | null,
    public client_email: string | null,
    public ville_signature: string,
    // Contract dates & status
    public date_contrat: string,
    public statut: ContractStatutType,
    // Project fields
    public adresse_travaux: string | null,
    public type_bien: ContractTypeBienType | string | null,
    public surface: number | null,
    public services: string[],
    public description_travaux: string | null,
    public date_debut: string | null,
    public duree_estimee: string | null,
    public conditions_acces: string | null,
    // Financial fields
    public montant_ht: number,
    public devise: ContractDeviseType | string,
    public tva: number,
    public readonly montant_tva: number,
    public readonly montant_ttc: number,
    public tranches: ContractTrancheType[],
    public mode_paiement_texte: ContractModePaiementTexteType | string | null,
    public rib: string | null,
    public delai_retard: number,
    public penalite_retard: number,
    public frais_redemarrage: number | null,
    // Clauses
    public garantie: ContractGarantieType | string,
    public delai_reserves: number,
    public tribunal: ContractTribunalType | string,
    public clauses_actives: string[],
    public clause_spec: string | null,
    public exclusions: string | null,
    // Options
    public type_contrat: ContractTypeType | string,
    public readonly type_contrat_display: string,
    public responsable_projet: string | null,
    public architecte: string | null,
    public confidentialite: ContractConfidentialiteType | string,
    public version_document: string,
    public annexes: string | null,
    // Blueline-specific fields
    public client_ville: string | null,
    public client_cp: string | null,
    public chantier_ville: string | null,
    public chantier_etage: string | null,
    public prestations: ContractPrestationType[] | null,
    public fournitures: ContractFournituresType | string | null,
    public materiaux_detail: string | null,
    public eau_electricite: ContractEauElectriciteType | string | null,
    public garantie_nb: number | null,
    public garantie_unite: ContractGarantieUniteType | string | null,
    public garantie_type: ContractGarantieTypeType | string | null,
    public exclusions_garantie: string | null,
    public acompte: number | null,
    public tranche2: number | null,
    public readonly solde: number | null,
    public clause_resiliation: ContractClauseResiliationType | string | null,
    public notes: string | null,
    // Sous-Traitance (CDL) specific fields
    public st_projet: number | null,
    public st_projet_detail: ProjectType | null,
    public st_name: string | null,
    public st_forme: STFormeJuridiqueType | string | null,
    public st_capital: string | null,
    public st_rc: string | null,
    public st_ice: string | null,
    public st_if: string | null,
    public st_cnss: string | null,
    public st_addr: string | null,
    public st_rep: string | null,
    public st_cin: string | null,
    public st_qualite: string | null,
    public st_tel: string | null,
    public st_email: string | null,
    public st_rib: string | null,
    public st_banque: string | null,
    public st_lot_type: string[] | null,
    public st_lot_description: string | null,
    public st_type_prix: string[] | null,
    public st_retenue_garantie: number | null,
    public st_avance: number | null,
    public st_penalite_taux: number | null,
    public st_plafond_penalite: number | null,
    public st_delai_paiement: number | null,
    public st_tranches: STTrancheType[],
    public st_delai_val: number | null,
    public st_delai_unit: STDelaiUnitType | string | null,
    public st_garantie_mois: number | null,
    public st_delai_reserves: number | null,
    public st_delai_med: number | null,
    public st_clauses_actives: string[],
    public st_observations: string | null,
    // Meta audit
    public readonly created_by_user: number | null,
    public readonly created_by_user_id: number | null,
    public readonly created_by_user_name: string | null,
    public readonly date_created: string,
    public readonly date_updated: string,
  ) {
  }
}
