import type {
	ContractCompanyType,
	ContractCategoryType,
	ContractStatutType,
	ContractTypeType,
	ContractTypeBienType,
	ContractClientQualiteType,
	ContractGarantieType,
	ContractTribunalType,
	ContractConfidentialiteType,
	ContractModePaiementTexteType,
	ContractDeviseType,
	ContractTrancheType,
	ContractFournituresType,
	ContractEauElectriciteType,
	ContractGarantieUniteType,
	ContractGarantieTypeType,
	ContractClauseResiliationType,
	ContractPrestationType,
	STLotType,
	STFormeJuridiqueType,
	STTypePrixType,
	STDelaiUnitType,
	STTrancheType,
	ProjectType,
} from '@/types/contractTypes';

export class UserClass {
	constructor(
		public readonly id: number,
		public first_name: string,
		public last_name: string,
		public email: string,
		public gender: string,
		public avatar: string | ArrayBuffer | null,
		public avatar_cropped: string | ArrayBuffer | null,
		public is_staff: boolean,
		public is_active: boolean,
		public default_password_set: boolean,
		public date_joined: string | null,
		public date_updated: string | null,
		public last_login: string | null,
		// Per-user permission flags
		public can_view: boolean,
		public can_print: boolean,
		public can_create: boolean,
		public can_edit: boolean,
		public can_delete: boolean,
	) {}
}

export class ContractClass {
	constructor(
		// Meta identifiers
		public readonly id: number,
		public numero_contrat: string,
		public readonly client_name: string | null,

		// Company
		public company: ContractCompanyType | string,
		public readonly company_display: string,
		public contract_category: ContractCategoryType | string,
		public readonly contract_category_display: string,

		// Client embedded fields
		public client_nom: string,
		public client_cin: string,
		public client_qualite: ContractClientQualiteType | string,
		public client_adresse: string,
		public client_tel: string,
		public client_email: string,
		public ville_signature: string,

		// Contract dates & status
		public date_contrat: string,
		public statut: ContractStatutType,

		// Project fields
		public adresse_travaux: string,
		public type_bien: ContractTypeBienType | string,
		public surface: number | null,
		public services: string[],
		public description_travaux: string,
		public date_debut: string | null,
		public duree_estimee: string,
		public conditions_acces: string,

		// Financial fields
		public montant_ht: number,
		public devise: ContractDeviseType | string,
		public tva: number,
		public readonly montant_tva: number,
		public readonly montant_ttc: number,
		public tranches: ContractTrancheType[],
		public mode_paiement_texte: ContractModePaiementTexteType | string,
		public rib: string,
		public delai_retard: number,
		public penalite_retard: number,
		public frais_redemarrage: number,

		// Clauses
		public garantie: ContractGarantieType | string,
		public delai_reserves: number,
		public tribunal: ContractTribunalType | string,
		public clauses_actives: string[],
		public clause_spec: string,
		public exclusions: string,

		// Options
		public type_contrat: ContractTypeType | string,
		public readonly type_contrat_display: string,
		public responsable_projet: string,
		public architecte: string,
		public confidentialite: ContractConfidentialiteType | string,
		public version_document: string,
		public annexes: string,

		// Blueline-specific fields
		public client_ville: string,
		public client_cp: string,
		public chantier_ville: string,
		public chantier_etage: string,
		public prestations: ContractPrestationType[] | null,
		public fournitures: ContractFournituresType | string,
		public materiaux_detail: string,
		public eau_electricite: ContractEauElectriciteType | string,
		public garantie_nb: number | null,
		public garantie_unite: ContractGarantieUniteType | string,
		public garantie_type: ContractGarantieTypeType | string,
		public exclusions_garantie: string,
		public acompte: number | null,
		public tranche2: number | null,
		public readonly solde: number | null,
		public clause_resiliation: ContractClauseResiliationType | string,
		public notes: string,

		// Sous-Traitance (CDL) specific fields
		public st_projet: number | null,
		public st_projet_detail: ProjectType | null,
		public st_name: string,
		public st_forme: STFormeJuridiqueType | string,
		public st_capital: string,
		public st_rc: string,
		public st_ice: string,
		public st_if: string,
		public st_cnss: string,
		public st_addr: string,
		public st_rep: string,
		public st_cin: string,
		public st_qualite: string,
		public st_tel: string,
		public st_email: string,
		public st_rib: string,
		public st_banque: string,
		public st_lot_type: STLotType | string,
		public st_lot_description: string,
		public st_type_prix: STTypePrixType | string,
		public st_retenue_garantie: number | null,
		public st_avance: number | null,
		public st_penalite_taux: number | null,
		public st_plafond_penalite: number | null,
		public st_delai_paiement: number | null,
		public st_tranches: STTrancheType[],
		public st_delai_val: number | null,
		public st_delai_unit: STDelaiUnitType | string,
		public st_garantie_mois: number | null,
		public st_delai_reserves: number | null,
		public st_delai_med: number | null,
		public st_clauses_actives: string[],
		public st_observations: string,

		// Meta audit
		public readonly created_by_user: number | null,
		public readonly created_by_user_id: number | null,
		public readonly created_by_user_name: string | null,
		public readonly date_created: string,
		public readonly date_updated: string,
	) {}
}
